### PR TITLE
Added ability to skip a commit on AppVeyor. 

### PR DESCRIPTION
**Pull request by StummeJ**
In AppVeyor you must define your message key.

### CODE REVIEW

**Comment by FelschR** [comment]
Do you know why there was no AppVeyor build created for this pull request?

**Comment by StummeJ** [comment]
The last commit message had [skip-ci] in it.

**Comment by FelschR** [comment]
AppVeyor seems to already support [ci skip] and [skip ci]:
https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message

**Comment by FelschR** [comment]
I'll just leave the default then. Also only ignoring commits for AppVeyor also works by using [skip appveyor].

**Pull request closed without merging**
