### PR TITLE
Support AppVeyor for CI & enable CI testing

### PR DESCRIPTION
**Pull request by StummeJ**
AppVeyor is free for open source project and runs on a Windows Server VM.  It has Visual Studio 2015 installed and allows for other software install as needed for building and testing.  It also supports automatic deployment to NuGet and creates a release for GitHub.  

For this project I have installed the DocumentDB Emulator, and queue both unit and integration tests to run on CI.  If the tests fail then the build will fail.  If everything passes then it will create a tag and release on GitHub, and release to NuGet.

#### Some setup is still required!
1) Create AppVeyor project for AspNetCore.Identity.DocumentDB
2) Encrypt your NuGet api key and GitHub access key via https://ci.appveyor.com/tools/encrypt
3) Modify the `appveyor.yml` file and replace any instance of `InsertEncryptedStringHere` with the new string from AppVeyor.

### CODE REVIEW

**Comment by StummeJ** [comment]
If you need any help with maintaining the appveyor job feel free to add me as a collaborator.  My AppVeyor name is the same as my GitHub name.

**Comment by FelschR** [comment]
Thanks once again!
AppVeyor's support for installing MSI's is a great feature I was looking for in some other CI tools but couldn't find.

The AppVeyor build is generally working now but the configuration seems to be somewhat faulty.
I added you as collaborator, maybe you can look into it.

**Comment by FelschR** [comment]
Found the issue and fixed it in 0de0438eab7109a5b564d7ccc64166339535af25.
There is still some error with Git tag creation I'll look into now.

**Comment by StummeJ** [comment]
Good catch! I actually found that syntax a few months back and couldn't figure it out again recently.

**Comment by FelschR** [comment]
Git tag creation is working now as well.
Artifacts are not properly stored though and ppVeyor is also only building for the .NETFramework and not .NETStandard target.

**Comment by StummeJ** [comment]
Hmm, does it build all of the frameworks when you do a `dotnet build src\aspnetcore.identity.documentdb`?

**Comment by StummeJ** [comment]
it looks like it's building both dlls:
```
dotnet build "src\AspNetCore.Identity.DocumentDB" -c ${env:CONFIGURATION} --version-suffix ${env:APPVEYOR_BUILD_NUMBER}
Project AspNetCore.Identity.DocumentDB (.NETFramework,Version=v4.5.1) will be compiled because expected outputs are missing
Compiling AspNetCore.Identity.DocumentDB for .NETFramework,Version=v4.5.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:03.3805208
 
Project AspNetCore.Identity.DocumentDB (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling AspNetCore.Identity.DocumentDB for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.2621811
 ```

**Comment by StummeJ** [comment]
Ahh I know what it is....  I'll submit another PR.

**Comment by FelschR** [comment]
I think I overlooked .NETStandard in the previous builds. Seems to be ok.

**Pull request merged**
